#Requires -Version 5.1
<#
.SYNOPSIS
    Regenerates docs/inventory.md: every project (counts, format version, group) and every group file.
.EXAMPLE
    .\tools\scripts\Update-DwInventory.ps1                       # scans '.\DriveWorks Files'
    .\tools\scripts\Update-DwInventory.ps1 -Path D:\somewhere\pkg -SourceLabel 'package extract'
#>
param(
    [string]$Path = (Join-Path $PSScriptRoot '..\..\DriveWorks Files'),
    [string]$OutFile = (Join-Path $PSScriptRoot '..\..\docs\inventory.md'),
    [string]$SourceLabel,
    [string]$ExcludePattern = '\\Restored Files\\'   # stale duplicates in the Sparta snapshot
)

Import-Module (Join-Path $PSScriptRoot '..\DwTools\DwTools.psm1') -Force
$root = (Resolve-Path -LiteralPath $Path).Path
if (-not $SourceLabel) { $SourceLabel = $root }

function ConvertTo-MdTable($rows, [string[]]$columns) {
    '| ' + ($columns -join ' | ') + ' |'
    '|' + (($columns | ForEach-Object { '---' }) -join '|') + '|'
    foreach ($r in $rows) { '| ' + (($columns | ForEach-Object { "$($r.$_)" -replace '\|', '\|' }) -join ' | ') + ' |' }
}
function Get-RelativePath([string]$full) { $full.Substring($root.Length).TrimStart('\') }

$projectFiles = Get-ChildItem -LiteralPath $root -Recurse -File -Filter *.driveprojx | Where-Object { $_.FullName -notmatch $ExcludePattern }
$projects = $projectFiles | ForEach-Object { Get-DwProjectSummary $_.FullName } | Sort-Object Project
foreach ($p in $projects) { $p | Add-Member NoteProperty File (Get-RelativePath $p.Path) }

$groups = foreach ($g in Get-ChildItem -LiteralPath $root -Recurse -File -Filter *.drivegroup | Where-Object { $_.FullName -notmatch $ExcludePattern }) {
    $format = Get-DwGroupFormat $g.FullName
    $registered = ''; $version = ''
    if ($format -eq 'SQLite') {
        $registered = @(Get-DwGroupProject $g.FullName).Count
        $v = @{}; Invoke-DwGroupQuery $g.FullName 'SELECT Name, Value FROM GroupProperties' | ForEach-Object { $v[$_.Name] = $_.Value }
        if ($v.Count) { $version = "$($v['GroupVersionMajor']).$($v['GroupVersionMinor']).$($v['GroupVersionRevision'])" }
    }
    [pscustomobject]@{ File = Get-RelativePath $g.FullName; Format = $format; GroupVersion = $version; RegisteredProjects = $registered; SizeKB = [math]::Round($g.Length / 1KB) }
}

$totals = [pscustomobject]@{
    Projects  = @($projects).Count
    Variables = ($projects | Measure-Object Variables -Sum).Sum
    Constants = ($projects | Measure-Object Constants -Sum).Sum
    Forms     = ($projects | Measure-Object Forms -Sum).Sum
    Controls  = ($projects | Measure-Object Controls -Sum).Sum
}

$md = @(
    '# DriveWorks inventory'
    ''
    "> Generated by ``tools/scripts/Update-DwInventory.ps1`` on $(Get-Date -Format 'yyyy-MM-dd HH:mm'). Do not edit by hand."
    "> Source: $SourceLabel"
    ''
    "**$($totals.Projects) projects** - $($totals.Variables) variables, $($totals.Constants) constants, $($totals.Forms) forms, $($totals.Controls) form controls."
    ''
    '## Projects'
    ''
    ConvertTo-MdTable $projects 'Project', 'FormatVersion', 'GroupServer', 'SizeKB', 'Variables', 'Constants', 'Forms', 'Controls', 'Documents', 'Macros', 'CalcTables', 'ComponentParts'
    ''
    '## Project files'
    ''
    ConvertTo-MdTable $projects 'Project', 'GroupName', 'File'
    ''
    '## Group files'
    ''
    ConvertTo-MdTable $groups 'File', 'Format', 'GroupVersion', 'RegisteredProjects', 'SizeKB'
    ''
)
$md | Set-Content -LiteralPath $OutFile -Encoding UTF8
Write-Host "Wrote $OutFile ($($totals.Projects) projects, $(@($groups).Count) groups)"
