#Requires -Version 5.1
<#
DwApi: runs real DriveWorks specifications in the SANDBOX group through the DriveWorks API (DriveWorks.Engine.dll from
the local install), with exact inputs, so a change can be validated by DriveWorks itself and then generated in
SOLIDWORKS.

Rules enforced here (user's, 2026-10-09):
  - only the sandbox group (Provider=LocalGroupProvider on DriveWorks Files\Sparta DW Group for Claude.drivegroup);
  - every spec Claude creates has a WO prefix starting with "CAI" (CAI01, CAI02, CAItestnoback...);
  - "Dev Release" is checked (there is no Autopilot on the dev group).
Credentials come from $env:DW_GROUP_USER / $env:DW_GROUP_PASSWORD; never write them anywhere.

A spec is a record in the group database written by DriveWorks itself. Releasing runs the flow: documents, emails
(to the ClientEmail / logged-in user) and data exports, like a user release. Models are generated by the user in
SOLIDWORKS (DriveWorks add-in) for now.
#>

Set-StrictMode -Off
$script:RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$script:SandboxGroup = Join-Path $script:RepoRoot 'DriveWorks Files\Sparta DW Group for Claude.drivegroup'

function Initialize-DwApi {
    if ($script:ApiReady) { return }
    $dir = Get-ChildItem 'C:\Program Files\DriveWorks' -Directory | Where-Object { $_.Name -match '^24\.' } | Sort-Object Name | Select-Object -Last 1
    if (-not $dir) { throw 'DriveWorks 24 is not installed under C:\Program Files\DriveWorks.' }
    $script:DllIndex = @{}
    Get-ChildItem -LiteralPath $dir.FullName -Recurse -Filter *.dll | Where-Object { $_.Name -notmatch '\.resources\.dll$' } | ForEach-Object { if (-not $script:DllIndex.ContainsKey($_.BaseName)) { $script:DllIndex[$_.BaseName] = $_.FullName } }
    $index = $script:DllIndex
    [AppDomain]::CurrentDomain.add_AssemblyResolve({ param($s, $e) $n = (New-Object Reflection.AssemblyName($e.Name)).Name; if ($index.ContainsKey($n)) { return [Reflection.Assembly]::LoadFrom($index[$n]) }; return $null }.GetNewClosure())
    [void][Reflection.Assembly]::LoadFrom($script:DllIndex['DriveWorks.Engine'])
    $script:ApiReady = $true
}

function Connect-DwGroup {
    <#
    .SYNOPSIS  Opens the sandbox group through the DriveWorks API. Returns a connection for New-DwSpec / Get-DwSpecValue;
               close it with Disconnect-DwGroup. Refuses any group other than the sandbox.
    #>
    param([string]$GroupFile = $script:SandboxGroup)
    Initialize-DwApi
    $full = (Resolve-Path -LiteralPath $GroupFile).Path
    if ($full -ne (Resolve-Path -LiteralPath $script:SandboxGroup).Path) { throw "Only the sandbox group may be opened: $script:SandboxGroup" }
    if (-not $env:DW_GROUP_USER -or -not $env:DW_GROUP_PASSWORD) { throw 'Set $env:DW_GROUP_USER and $env:DW_GROUP_PASSWORD for this session first.' }
    $h = New-Object DriveWorks.Hosting.EngineHost
    $gm = $h.CreateGroupManager()
    try { $gm.OpenGroup("Provider=LocalGroupProvider;Path=$full;", $env:DW_GROUP_USER, $env:DW_GROUP_PASSWORD) }
    catch { $gm.Dispose(); $h.Dispose(); throw }
    [pscustomobject]@{ Host = $h; Manager = $gm; Group = $gm.Group; Contexts = (New-Object System.Collections.Generic.List[object]) }
}

function Disconnect-DwGroup {
    param([Parameter(Mandatory, Position = 0)]$Connection)
    foreach ($c in $Connection.Contexts) { try { if ($c.IsLoaded) { $c.Cancel($false) } } catch { } }
    try { $Connection.Manager.CloseGroup() } catch { }
    $Connection.Manager.Dispose(); $Connection.Host.Dispose()
}

function New-DwSpec {
    <#
    .SYNOPSIS  Starts a new specification of a project in the sandbox, drives exact inputs (control name -> value, as a
               user would type them), and optionally invokes a transition ('Save', 'ReleaseLocal', ...).
               Enforces: WOPrefix starts with CAI, DevRelease = TRUE (when the project has those controls).
    .EXAMPLE   $c = Connect-DwGroup; $s = New-DwSpec $c 'DW Hopper V2' @{ WOPrefix='CAI01'; DevRelease=$true; DropZoneLengthRight=6 } -Transition Save
    #>
    param(
        [Parameter(Mandatory, Position = 0)]$Connection, [Parameter(Mandatory, Position = 1)][string]$Project,
        [Parameter(Mandatory, Position = 2)][hashtable]$Inputs, [string]$Transition
    )
    $pd = $null
    if (-not $Connection.Group.Projects.TryGetProject($Project, [ref]$pd)) { throw "No project '$Project' in the sandbox group." }
    $wo = $Inputs['WOPrefix']
    if ($null -ne $wo -and "$wo" -notmatch '^CAI') { throw "WOPrefix '$wo' must start with CAI (Claude AI tests)." }
    $env = New-Object DriveWorks.Specification.SpecificationEnvironment
    # CreateSpecificationContext makes its temporary folder under this path (null -> Path.Combine fails).
    $tmp = Join-Path $script:RepoRoot 'work\dwapi-temp'
    New-Item -ItemType Directory -Force -Path $tmp | Out-Null
    $env.TemporaryFolderPath = $tmp
    # Specs go where the group puts them (DriveWorks Files\Specifications), so the user finds them in SOLIDWORKS.
    $env.SpecificationBasePath = $Connection.Group.DefaultSpecificationFolder
    $ctx = $Connection.Host.CreateSpecificationContext($Connection.Group, $env)
    $Connection.Contexts.Add($ctx)
    $ctx.Start($pd)
    # DriveInputs takes text, as typed: True/False for check boxes, invariant numbers.
    if ($Inputs.ContainsKey('DevRelease') -and -not [bool]$Inputs['DevRelease']) { throw 'DevRelease must be checked on the dev group.' }
    $d = New-Object 'System.Collections.Generic.Dictionary[string,string]'
    foreach ($k in $Inputs.Keys) {
        $v = $Inputs[$k]
        $d[$k] = if ($v -is [bool]) { if ($v) { 'True' } else { 'False' } } elseif ($v -is [double] -or $v -is [int] -or $v -is [decimal]) { ([double]$v).ToString([Globalization.CultureInfo]::InvariantCulture) } else { [string]$v }
    }
    if (-not $d.ContainsKey('DevRelease')) { $d['DevRelease'] = 'True' }
    $ctx.DriveInputs($d)
    $result = [pscustomobject]@{ Context = $ctx; Name = $ctx.SpecificationName; Id = $ctx.Id; Directory = $ctx.SpecificationDirectory; State = $(if ($ctx.CurrentState) { $ctx.CurrentState.Title }); Transitions = @($ctx.GetTransitions() | ForEach-Object { "$_" }); TransitionResult = $null }
    if ($Transition) {
        $result.TransitionResult = $ctx.InvokeTransition($Transition)
        $result.Name = $ctx.SpecificationName; $result.Id = $ctx.Id; $result.Directory = $ctx.SpecificationDirectory
        $result.State = $(if ($ctx.CurrentState) { $ctx.CurrentState.Title })
    }
    $result
}

function Invoke-DwSpecTransition {
    <#
    .SYNOPSIS  Reopens a saved CAI test spec and runs a transition: Edit first when it is Saved, then -Transition
               (default ReleaseLocal). Returns the state, the folder, the Panels-style specs it released, the queued
               components (generation) and the deferred tasks (emails).
               ReleaseLocal is used rather than the Release macro: the macro releases locally only when Dev Release
               is effective, and Dev Release is forced off for users outside the Developement team.
    .EXAMPLE   $c = Connect-DwGroup; try { Invoke-DwSpecTransition $c 'CAI01-Hopper 0008' } finally { Disconnect-DwGroup $c }
    #>
    param([Parameter(Mandatory, Position = 0)]$Connection, [Parameter(Mandatory, Position = 1)][string]$SpecName, [string]$Transition = 'ReleaseLocal')
    $det = $Connection.Group.Specifications.GetSpecification($SpecName)
    if ($det.Name -notmatch '^CAI') { throw "Refusing: '$($det.Name)' is not a CAI test spec." }
    $before = @($Connection.Group.Specifications.GetSpecificationsByModifiedDate($true) | ForEach-Object Id)
    $env = New-Object DriveWorks.Specification.SpecificationEnvironment
    $tmp = Join-Path $script:RepoRoot 'work\dwapi-temp'; New-Item -ItemType Directory -Force -Path $tmp | Out-Null
    $env.TemporaryFolderPath = $tmp; $env.SpecificationBasePath = $Connection.Group.DefaultSpecificationFolder
    $ctx = $Connection.Host.CreateSpecificationContext($Connection.Group, $env); $Connection.Contexts.Add($ctx)
    $ctx.Open($det)
    if ($ctx.CurrentState.Title -eq 'Saved' -and $Transition -ne 'Edit') { [void]$ctx.InvokeTransition('Edit') }
    $ok = $ctx.InvokeTransition($Transition)
    $new = @($Connection.Group.Specifications.GetSpecificationsByModifiedDate($true) | Where-Object { $before -notcontains $_.Id })
    [pscustomobject]@{
        Spec = $ctx.SpecificationName; Id = $ctx.Id; Result = $ok; State = $ctx.CurrentState.Title; Folder = $ctx.SpecificationDirectory
        NewSpecs = @($new | ForEach-Object { "$($_.Name) [$($_.StateName)]" })
        Components = @($Connection.Group.Specifications.GetSpecificationComponents($ctx.Id, $false))
        Tasks = @($Connection.Group.Specifications.GetTasksForSpecification($ctx.Id) | ForEach-Object { $_.Type -replace '^.*/', '' })
    }
}

function Get-DwSpecValue {
    <#
    .SYNOPSIS  Variable values of a running specification (from New-DwSpec), as DriveWorks computed them.
    .EXAMPLE   Get-DwSpecValue $s.Context -Name 'DZLength*'
    #>
    param([Parameter(Mandatory, Position = 0)]$Context, [string]$Name = '*')
    foreach ($v in $Context.Project.Variables.GetVariables()) {
        if ($v.DisplayName -notlike $Name) { continue }
        $val = $v.Value
        $txt = if ($null -eq $val) { '' } elseif ($val -is [double]) { $val.ToString([Globalization.CultureInfo]::InvariantCulture) } elseif ($val -is [bool]) { if ($val) { 'TRUE' } else { 'FALSE' } } else { "$val" }
        [pscustomobject]@{ Name = $v.DisplayName; Value = $txt }
    }
}

Export-ModuleMember -Function Connect-DwGroup, Disconnect-DwGroup, New-DwSpec, Invoke-DwSpecTransition, Get-DwSpecValue
